---
title: "Football leagues predictability"
output: html_notebook
---

#### Retreiving the information about leagues
```{r}
library("RSQLite")
library('entropy')
library('ggplot2')

con <- dbConnect(drv=RSQLite::SQLite(), dbname="database.sqlite")
all.leagues <- dbGetQuery(conn=con, statement="SELECT * FROM 'League' ")
print(all.leagues)
```

#### Picking some leagues

```{r}
leagues <- data.frame(league_name=character(), 
                 league_id=integer(),  stringsAsFactors=FALSE) 
leagues[1, ] <-  c('England', 1729)
leagues[2, ] <- c('France', 4769)
leagues[3, ] <- c('Germany', 7809)
leagues[4, ] <- c('Italy', 10257)
leagues[5, ] <- c('Spain', 21518)

leagues

```


#### Retreiving odds for all matches in selected leagues


```{r}
league.ids  <- paste(leagues[ , 2], collapse = ', ')
table  <- dbGetQuery(conn=con, statement=paste("SELECT * FROM Match WHERE league_id IN (" , league.ids , ")", sep=""))
matches = table[, c("id", "league_id", "season", "home_team_api_id", "away_team_api_id",  'B365H', 'B365D' ,'B365A' )]
dbDisconnect(con)
head(matches)
```

#### For each match computing entropy of odds by different agencies

```{r}

matchEntropy <- function(row) {
  odds = row[c('B365H' ,'B365D', 'B365A')]
  probs <- vapply(as.numeric(odds), function(x) 1 / x , 1)
  probs_sum <- sum(probs, na.rm = TRUE)
  norm_probs <- vapply(probs, function(x) x / probs_sum , 1)
  entropy(norm_probs, na.rm = TRUE)
} 

matches["entropy"] <- apply(matches, 1, matchEntropy)
head(matches)

```

#### Computing mean entropy across all leagues and individual teams

```{r}

home.matches <- subset(matches, select=c("league_id", "home_team_api_id", "season", "entropy"))
names(home.matches)[2] <- 'team_id'

guest.matches <- subset(matches, select=c("league_id", "away_team_api_id", "season", "entropy"))
names(guest.matches)[2] <- 'team_id'
allmatches <- rbind(home.matches, guest.matches)

team.entropy <- aggregate(allmatches$entropy,
          list(league_id = allmatches$league_id,
               team = allmatches$team_id,
               season = allmatches$season),
          FUN = function(x) mean(x, na.rm=TRUE))

league.entropy <- aggregate(matches$entropy,
          list(league_id = matches$league_id, season = matches$season),
          FUN = function(x) mean(x, na.rm=TRUE))

print(league.entropy)

#set name to entropy column
names(team.entropy)[4] <- 'ent'
names(league.entropy)[3] <- 'ent'

#add human-readable league names
team.entropy <- merge(team.entropy, leagues, by = "league_id")
league.entropy <- merge(league.entropy, leagues, by = "league_id")
head(team.entropy)
head(league.entropy)

```

#### And plots

```{r}

colors <- c("blue", "green", "red", "violet", "yellow")

ggplot(dat = league.entropy, aes(x=season, y = ent)) + 
  geom_line(aes(colour=league_name, group=league_name)) + 
  geom_point(aes(colour=league_name, group=league_name)) + 
  scale_colour_manual(values = colors) + 
    xlab("Season") + ylab("Average entropy") +
    ggtitle("Average entropy by league") + 
   annotate("text", x = 4, y = 1.035, label = "less predictable") +
   annotate("text", x = 4, y = 0.93, label = "more predictable")

ggplot(dat = team.entropy, aes(x=season, y = ent)) + 
  geom_point(aes(colour=league_name, group=league_name), position = position_dodge(width = 0.5)) + 
  scale_colour_manual(values = colors) + 
  xlab("Season") + ylab("Average entropy")  +
  ggtitle("Average entropy by team")  +
  annotate("text", x = 4, y = 1.1, label = "less predictable") +
  annotate("text", x = 4, y = 0.6, label = "more predictable") + 
  annotate("text", x = 7.8, y = 0.64, label = "Barcelona", size = 2.2) + 
  annotate("text", x = 7.65, y = 0.65, label = "B.Munich", size  = 2.2) +
  annotate("text", x = 7.75, y = 0.73, label = "Real Madrid", size  = 2.2) + 
  annotate("text", x = 7.67, y = 0.79, label = "PSG", size  = 2.2)



```

