---
title: "Football leagues predictability"
output: html_notebook
---

#### Reading the data about leagues and matches, retrieved in Quantlet 1
```{r}
library("entropy")
library("rio")

leagues = import("leagues.rds")
matches = import("matches.rds")
```


#### Computing entropy of odds for each match

```{r}
MatchEntropy = function(row) {
    odds = row[c("B365H", "B365D", "B365A")]
    probs = vapply(as.numeric(odds), function(x) 1/x, 1)
    probs_sum = sum(probs, na.rm = TRUE)
    norm_probs = vapply(probs, function(x) x/probs_sum, 1)
    entropy(norm_probs, na.rm = TRUE)
}

matches["entropy"] = apply(matches, 1, MatchEntropy)
head(matches)
```

#### Computing mean entropy across all leagues and individual teams and exporting data

```{r}
home.matches = subset(matches, select = c("league_id", "home_team_api_id", 
    "season", "entropy"))
names(home.matches)[2] = "team_id"

guest.matches = subset(matches, select = c("league_id", "away_team_api_id", 
    "season", "entropy"))
names(guest.matches)[2] = "team_id"
all.matches = rbind(home.matches, guest.matches)

team.entropy = aggregate(all.matches$entropy, list(league_id = all.matches$league_id, 
    team = all.matches$team_id, season = all.matches$season), FUN = function(x) mean(x, 
    na.rm = TRUE))

league.entropy = aggregate(matches$entropy, list(league_id = matches$league_id, 
    season = matches$season), FUN = function(x) mean(x, na.rm = TRUE))

print(league.entropy)

# set name to entropy column
names(team.entropy)[4] = "ent"
names(league.entropy)[3] = "ent"

# add human-readable league names
team.entropy = merge(team.entropy, leagues, by = "league_id")
league.entropy = merge(league.entropy, leagues, by = "league_id")
head(team.entropy)
head(league.entropy)
export(team.entropy, "team_entropy.rds")
export(league.entropy, "league_entropy.rds")
```

